(in-ns 'lambdaisland.witchcraft)
(require '[lambdaisland.data-printers :as dp])
#_(import (net.glowstone GlowWorld GlowServer GlowOfflinePlayer)
          (net.glowstone.block.entity.state GlowDispenser)
          (net.glowstone.chunk ChunkManager)
          (net.glowstone.constants GlowEnchantment GlowPotionEffect)
          (net.glowstone.io WorldStorageProvider)
          (net.glowstone.util.config WorldConfig ServerConfig)
          (org.bukkit Bukkit Material Location World)
          (org.bukkit.block Block)
          (org.bukkit.configuration.serialization ConfigurationSerialization)
          (org.bukkit.enchantments Enchantment)
          (org.bukkit.entity Entity Player HumanEntity)
          (org.bukkit.inventory ItemStack Inventory)
          (org.bukkit.material MaterialData Directional)
          (org.bukkit.plugin PluginManager Plugin)
          (org.bukkit.potion Potion PotionEffectType)
          (org.bukkit.scheduler BukkitScheduler)
          (org.bukkit.util Vector))

(defn defprint [type tag to-edn]
  (dp/register-print type tag to-edn)
  (dp/register-pprint type tag to-edn))

(defprint Location 'bukkit/Location #(do [(x %) (y %) (z %) (yaw %) (pitch %) (.getName (world %))]))
(defprint Block 'bukkit/Block #(do {:x (x %)
                                    :y (y %)
                                    :z (z %)
                                    :world (.getName (world %))
                                    :material (material-name %)
                                    :data (material-data %)}))
